version: '3'

services:
  compiler:
    image: ethereum/solc:0.8.17
    volumes:
      - ./contracts:/contracts
    command: --output-dir /contracts/build --overwrite --abi --bin /contracts/HistoryContract.sol

  deployer:
    image: ethereum/solc:0.8.17
    volumes:
      - ./build:/build
      - ./deploy:/deploy
    command: --abi /build/*.abi --bin /build/*.bin --optimize --overwrite --combined-json abi,bin,bin-runtime,srcmap,srcmap-runtime,ast,metadata /deploy/*.sol

  abi-gen:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./contracts:/contracts
      - ./internal:/internal
    command: abigen --abi /contracts/build/HistoryContract.abi --pkg history_contract --out /internal/pkg/history_contract/history_contract.go